[package]
name = "rscap"
description = "Rust based pcap for MpegTS and SMPTE2110 UDP/TCP Broadcast Feeds"
keywords = ["broadcast", "mpegts", "capture", "pcap", "zeromq"]
categories = ["command-line-utilities"]
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/groovybits/wiki"
repository = "https://github.com/groovybits/rscap"
authors = ["Chris Kennedy"]
version = "0.2.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = []
dpdk_enabled = ["capsule"]

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
capsule = { version = "0.1.5", optional = true }
pcap = { version = "1.1.0", features = ["all-features", "capture-stream"] }
futures = "0.3"
zmq = "0.10.0"
async_zmq = "0.4.0"
log = "0.4"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
lazy_static = "1.4.0"
rtp-rs = "0.6.0"
clap = { version = "4.4.11", features = ["derive", "env"] }
capnp = "0.18.0"
kafka = "0.9.0"
protobuf = "3.3.0"
protobuf-codegen-pure = "2.28.0"
serde = { version = "1.0.195", features = ["derive" ] }
serde_json = "1.0.111"
anyhow = "1.0.79"

[build-dependencies]
capnpc = "0.18.0"
#protobuf-codegen = "3.3.0"
protobuf-codegen-pure = "2.28.0"
#protobuf-parse = "3.3.0"
