[package]
name = "rscap"
description = "Rust based pcap for MpegTS and SMPTE2110 UDP/TCP Broadcast Feeds"
keywords = ["broadcast", "mpegts", "capture", "pcap", "zeromq"]
categories = ["command-line-utilities"]
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/groovybits/wiki"
repository = "https://github.com/groovybits/rscap"
authors = ["Chris Kennedy"]
version = "0.5.27"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = []
dpdk_enabled = ["capsule"]
gst = ["gstreamer", "gstreamer-app", "gstreamer-video"]

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
capsule = { version = "0.1.5", optional = true }
pcap = { version = "1.1.0", features = ["all-features", "capture-stream"] }
futures = "0.3"
zmq = "0.10.0"
async_zmq = "0.4.0"
log = "0.4"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
lazy_static = "1.4.0"
rtp-rs = "0.6.0"
clap = { version = "4.4.11", features = ["derive", "env"] }
capnp = "0.18.0"
kafka = "0.9.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
anyhow = "1.0.79"
h264-reader = "0.7.0"
sysinfo = "0.23.9"
once_cell = "1.5.2"
ahash = "0.8.7"
mpeg2ts-reader = "0.15.0"
scte35-reader = "0.14.0"
hex-slice = "0.1.4"
chrono = "0.4.37"
rdkafka = "0.36.2"
gstreamer = { version = "0.20", optional = true }
gstreamer-app = { version = "0.20", optional = true }
gstreamer-video = { version = "0.20", optional = true }
crossbeam = "0.8.4"
image = "0.25.1"
num_cpus = "1.16.0"
threadpool = "1.8.1"
base64 = "0.22.0"
rusttype = "0.9.3"
imageproc = "0.24.0"
ab_glyph = "0.2.24"
datetime = "0.5.2"

[build-dependencies]
capnpc = "0.18.0"
