[package]
name = "rscap"
description = "Rust based pcap for MpegTS and SMPTE2110 UDP/TCP Broadcast Feeds"
keywords = ["broadcast", "mpegts", "capture", "pcap", "zeromq"]
categories = ["command-line-utilities"]
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/groovybits/wiki"
repository = "https://github.com/groovybits/rscap"
authors = ["Chris Kennedy"]
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
rustflags = ["-C", "symbol-mangling-version=v0"]

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
pcap = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zmq = "0.10.0"
log = "0.4"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
lazy_static = "1.4.0"
rtp-rs = "0.6.0"
clap = { version = "4.4.11", features = ["derive", "env"] }
