[package]
name = "rscap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "1.1.0"
serde = "1.0"
serde_json = "1.0"
zmq = "0.10.0"
log = "0.4"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }

