name: Rust

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev libzmq3-dev capnproto
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
